car_shop/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import CarViewSet, CommentViewSet

app_name = 'api'

cars_router = DefaultRouter()
cars_router.register('cars', CarViewSet, basename='cars')

comment_router = DefaultRouter()
comment_router.register('comments', CommentViewSet, basename='comments')

urlpatterns = [
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('', include(cars_router.urls)),
    path('cars/<int:car_id>/', include(comment_router.urls)),
]

car_shop/car_shop/urls.py
from django.contrib.auth import get_user_model
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.urls import include, path, reverse_lazy


User = get_user_model()

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            model=User,
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('shop:index'),
        ),
        name='registration',
    ),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

car_shop/shop/urls.py
from django.urls import path

from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.IndexListView.as_view(),
         name='index'),
    path('cars/create/', views.CarCreateView.as_view(),
         name='create_car'),
    path('cars/<int:car_id>/', views.CarDetailView.as_view(),
         name='car_detail'),
    path('cars/<int:car_id>/edit/', views.CarUpdateView.as_view(),
         name='edit_car'),
    path('cars/<int:car_id>/delete/', views.CarDeleteView.as_view(),
         name='delete_car'),
    path('cars/<int:car_id>/comment/', views.CommentCreateView.as_view(),
         name='add_comment'),
]

car_shop/shop/models.py
from django.contrib.auth import get_user_model
from django.db import models

from .constans import TEXT_LIMIT, MAX_LENGTH


User = get_user_model()


class Car(models.Model):
    '''Model for cars.'''
    make = models.CharField(max_length=MAX_LENGTH, verbose_name='Марка')
    model = models.CharField(max_length=MAX_LENGTH, verbose_name='Модель')
    year = models.IntegerField(
        blank=True, null=True, verbose_name='Год выпуска'
    )
    description = models.TextField(verbose_name='Описание')
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Добавлено'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        null=True,
        blank=True,
        verbose_name='Обновлено'
    )
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='Владелец автомобиля'
    )

    class Meta:
        ordering = ('-updated_at', '-created_at')
        default_related_name = 'cars'
        verbose_name = 'автомобиль'
        verbose_name_plural = 'Автомобили'

    def __str__(self):
        return f'{self.make[:TEXT_LIMIT]}'


class Comment(models.Model):
    '''Model for comments.'''
    content = models.TextField(verbose_name='Содержание')
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name='Добавлено'
    )
    car = models.ForeignKey(
        Car,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f'{self.make[:TEXT_LIMIT]}'

car_shop/shop/forms.py
from django import forms

from .models import Car, Comment


class CarForm(forms.ModelForm):
    '''Form for cars.'''

    class Meta:
        model = Car
        exclude = ('owner', 'created_at', 'updated_at',)


class CommentForm(forms.ModelForm):
    '''Form for comments.'''

    class Meta:
        model = Comment
        fields = ('content',)

car_shop/shop/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django.urls import reverse, reverse_lazy

from .forms import CarForm, CommentForm
from .mixins import CarDispatchMixin
from .constans import DISPLAYED_CARS
from .models import Car, Comment


User = get_user_model()


def get_query_set(model_objects):
    '''Get basic object's queryset.'''
    return model_objects.select_related('owner').annotate(
        comment_count=Count('comments')
    )


class IndexListView(ListView):
    '''View for main page.'''
    model = Car
    template_name = 'shop/index.html'

    queryset = get_query_set(Car.objects).order_by(
        '-updated_at', '-created_at'
    )

    paginate_by = DISPLAYED_CARS


class CarDetailView(DetailView):
    '''View for detail car's information.'''
    model = Car
    template_name = 'shop/detail.html'

    def get_queryset(self):
        return get_query_set(Car.objects)

    def get_object(self):
        return get_object_or_404(
            self.get_queryset(), pk=self.kwargs.get('car_id')
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        context['comments'] = self.object.comments.select_related('author')
        return context


class CarCreateView(LoginRequiredMixin, CreateView):
    '''View for creating car.'''
    model = Car
    template_name = 'shop/create.html'
    form_class = CarForm

    def get_success_url(self):
        return reverse('shop:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class CarUpdateView(CarDispatchMixin, UpdateView):
    '''View for modifying car.'''
    model = Car
    template_name = 'shop/create.html'
    form_class = CarForm

    def get_success_url(self):
        return reverse(
            'shop:car_detail', kwargs={'car_id': self.kwargs.get('car_id')}
        )

    def get_object(self):
        return get_object_or_404(
            Car,
            pk=self.kwargs.get('car_id'),
            owner=self.request.user
        )


class CarDeleteView(CarDispatchMixin, DeleteView):
    '''View for deleting car.'''
    model = Car
    template_name = 'shop/create.html'
    queryset = Car.objects.all()
    success_url = reverse_lazy('shop:index')

    def get_object(self):
        return get_object_or_404(
            self.queryset,
            pk=self.kwargs.get('car_id'),
            owner=self.request.user
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        instance = self.object
        context['form'] = CarForm(
            self.request.POST, instance=instance
        )
        return context


class CommentCreateView(LoginRequiredMixin, CreateView):
    '''View for creating comment.'''
    model = Comment
    form_class = CommentForm

    def get_success_url(self):
        return reverse(
            'shop:car_detail', kwargs={'car_id': self.kwargs.get('car_id')}
        )

    def get_object(self):
        car = get_object_or_404(
            Car,
            pk=self.kwargs.get('car_id'),
        )
        return car

    def form_valid(self, form):
        form.instance.car = self.get_object()
        form.instance.author = self.request.user
        return super().form_valid(form)

car_shop/templates/shop/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit/' in request.path %}
    Редактирование автомобиля
  {% elif "/delete/" in request.path %}
    Удаление автомобиля
  {% else %}
    Добавление автомобиля
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if '/edit/' in request.path %}
          Редактирование автомобиля
        {% elif '/delete/' in request.path %}
          Удаление автомобиля
        {% else %}
          Добавление автомобиля
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if not '/delete/' in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <article>
              <h3>{{ form.instance.make }}</h3>
              <h3>{{ form.instance.model }}</h3>
              <h3>{{ form.instance.year }}</h3>
              <p>{{ form.instance.description|linebreaksbr }}</p>
            </article>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

car_shop/templates/shop/detail.html
{% extends "base.html" %}
{% block title %}
  {{ car.make }} {{ car.model }}
  {{ car.created_at|date:"d E Y" }}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        <h5 class="card-title">{{ car.make }} {{ car.model }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {{ car.pub_date|date:"d E Y, H:i" }}
            От автора @{{ car.owner.username }}
          </small>
        </h6>
        <p class="card-text">{{ car.description|linebreaksbr }}</p>
        {% if user == car.owner %}
          <div class="mb-2">
            <a class="btn btn-sm text-muted" href="{% url 'shop:edit_car' car.id %}" role="button">
              Отредактировать автомобиль
            </a>
            <a class="btn btn-sm text-muted" href="{% url 'shop:delete_car' car.id %}" role="button">
              Удалить автомобиль
            </a>
          </div>
        {% endif %}
        {% include "includes/comments.html" %}
      </div>
    </div>
  </div>
{% endblock %}

car_shop/templates/shop/index.html
{% extends "base.html" %}
{% block title %}
  Лента записей
{% endblock %}
{% block content %}
  {% for car in page_obj %}
    <article class="mb-5">
      {% include "includes/car_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}