car_shop/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import CarViewSet, CommentViewSet

app_name = 'api'

cars_router = DefaultRouter()
cars_router.register('cars', CarViewSet, basename='cars')

comment_router = DefaultRouter()
comment_router.register('comments', CommentViewSet, basename='comments')

urlpatterns = [
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('', include(cars_router.urls)),
    path('cars/<int:car_id>/', include(comment_router.urls)),
]

car_shop/car_shop/urls.py
from django.contrib.auth import get_user_model
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.urls import include, path, reverse_lazy


User = get_user_model()

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            model=User,
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('shop:index'),
        ),
        name='registration',
    ),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

car_shop/shop/urls.py
from django.urls import path

from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.IndexListView.as_view(),
         name='index'),
    path('cars/create/', views.CarCreateView.as_view(),
         name='create_car'),
    path('cars/<int:car_id>/', views.CarDetailView.as_view(),
         name='car_detail'),
    path('cars/<int:car_id>/edit/', views.CarUpdateView.as_view(),
         name='edit_car'),
    path('cars/<int:car_id>/delete/', views.CarDeleteView.as_view(),
         name='delete_car'),
    path('cars/<int:car_id>/comment/', views.CommentCreateView.as_view(),
         name='add_comment'),
]

car_shop/templates/includes/car_card.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      <h5 class="card-title">{{ car.make }} {{ car.model }}</h5>
      <p class="card-text">{{ car.description|truncatewords:10 }}</p>
      <a href="{% url 'shop:car_detail' car.id %}" class="card-link">Подробная информация</a>
      <em class="card-link text-muted">Комментарии ({{ car.comment_count }})</em>
    </div>
  </div>
</div>

car_shop/templates/includes/comments.html
{% if user.is_authenticated %}
  {% load django_bootstrap5 %}
  <h5 class="mb-4">Оставить комментарий</h5>
  <form method="post" action="{% url 'shop:add_comment' car.id %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Отправить" %}
  </form>
{% endif %}
<br>
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
          @{{ comment.author.username }}
      </h5>
      <small class="text-muted">{{ comment.created_at }}</small>
      <br>
      {{ comment.content|linebreaksbr }}
    </div>
  </div>
{% endfor %}

car_shop/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>АвтоБлокнот</p>
</footer>

car_shop/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'shop:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        АвтоБлокнот
      </a>
      {% if user.is_authenticated %}
        <div class="btn-group" role="group" aria-label="Basic outlined example">
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'shop:create_car' %}">Добавить автомобиль</a></button>
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'logout' %}">Выйти</a></button>
        </div>
      {% else %}
        <div class="btn-group" role="group" aria-label="Basic outlined example">
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'login' %}">Войти</a></button>
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'registration' %}">Регистрация</a></button>
        </div>
      {% endif %}
    </div>
  </nav>
</header>

car_shop/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}